/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import java.awt.Frame;
import timbiriche.Cliente;
import timbiriche.Jugador;
import controles.IFacadaDeNegocio;
import javax.swing.JOptionPane;
import timbiriche.Avatar;

/**
 *
 * @author rene_
 */
public class FrameRegistro extends javax.swing.JDialog {
    
    private static FrameRegistro pantallaRegistro;
    private Cliente jugador;
    private IFacadaDeNegocio facadaDeControl;
    
    /**
     * Creates new form PantallaRegistro
     * @param parent
     * @param modal
     * @param jugador
     * @param facadaDeControl
     */
    public FrameRegistro(java.awt.Frame parent, boolean modal, Cliente jugador, IFacadaDeNegocio facadaDeControl) {
        super(parent, modal);
        initComponents();
        this.jugador = jugador;
        this.facadaDeControl = facadaDeControl;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton_Registrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton_Imagen1 = new javax.swing.JRadioButton();
        jRadioButton_Imagen2 = new javax.swing.JRadioButton();
        jRadioButton_Imagen3 = new javax.swing.JRadioButton();
        jRadioButton_Imagen4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jTextField1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton_Registrar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton_Registrar.setText("Registrarse");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton_Imagen1);
        jRadioButton_Imagen1.setContentAreaFilled(false);
        jRadioButton_Imagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N
        jRadioButton_Imagen1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.1.png"))); // NOI18N
        jRadioButton_Imagen1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.1.png"))); // NOI18N
        jRadioButton_Imagen1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.1.png"))); // NOI18N
        jRadioButton_Imagen1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jRadioButton_Imagen1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton_Imagen2);
        jRadioButton_Imagen2.setContentAreaFilled(false);
        jRadioButton_Imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.png"))); // NOI18N
        jRadioButton_Imagen2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.1.png"))); // NOI18N
        jRadioButton_Imagen2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.1.png"))); // NOI18N
        jRadioButton_Imagen2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.1.png"))); // NOI18N
        jRadioButton_Imagen2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jRadioButton_Imagen2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton_Imagen3);
        jRadioButton_Imagen3.setContentAreaFilled(false);
        jRadioButton_Imagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.png"))); // NOI18N
        jRadioButton_Imagen3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.1.png"))); // NOI18N
        jRadioButton_Imagen3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.1.png"))); // NOI18N
        jRadioButton_Imagen3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen3.1.png"))); // NOI18N
        jRadioButton_Imagen3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jRadioButton_Imagen3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton_Imagen4);
        jRadioButton_Imagen4.setContentAreaFilled(false);
        jRadioButton_Imagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton_Imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen4.png"))); // NOI18N
        jRadioButton_Imagen4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen4.1.png"))); // NOI18N
        jRadioButton_Imagen4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen4.1.png"))); // NOI18N
        jRadioButton_Imagen4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen4.1.png"))); // NOI18N
        jRadioButton_Imagen4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jRadioButton_Imagen4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton_Imagen1)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton_Imagen2)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton_Imagen3)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton_Imagen4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton_Imagen1)
                        .addComponent(jRadioButton_Imagen3)
                        .addComponent(jRadioButton_Imagen4)
                        .addComponent(jRadioButton_Imagen2))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jButton_Registrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(74, 74, 74)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton_Registrar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        //Validar textFields
        
        ((Jugador) this.jugador).setNombre(jTextField1.getText().trim());
        this.asignarPersonaje();
        try {
            this.facadaDeControl.guardarJugador(this.jugador);
            this.mostrarMensaje("Has sido registrado correctamente "+ ((Jugador) this.jugador).getNombre(), "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception ex) {
            this.mostrarMensaje(ex.getMessage(), "Mensaje", JOptionPane.OK_OPTION);
            ((Jugador) this.jugador).setAvatar(null);
            ((Jugador) this.jugador).setNombre(null);
        }
        
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
       if(jTextField1.getText().length() >= 10){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField1KeyTyped
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_Imagen1;
    private javax.swing.JRadioButton jRadioButton_Imagen2;
    private javax.swing.JRadioButton jRadioButton_Imagen3;
    private javax.swing.JRadioButton jRadioButton_Imagen4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
   
    public void mostrarPantalla() {
        this.jTextField1.setText("");
        this.setVisible(true);
    }
    
    public static FrameRegistro getInstacia(Frame parent, boolean modal, Cliente jugador, IFacadaDeNegocio facadaDeControl) {
        if (pantallaRegistro == null) {
            pantallaRegistro = new FrameRegistro(parent, modal, jugador, facadaDeControl);
        }
        return pantallaRegistro;
    }
    
    public void asignarPersonaje() {        
        if(this.jRadioButton_Imagen1.isSelected()) {
            ((Jugador) this.jugador).setAvatar(new Avatar(this.jRadioButton_Imagen1.getIcon()));
        } else if(this.jRadioButton_Imagen2.isSelected()) {
            ((Jugador) this.jugador).setAvatar(new Avatar(this.jRadioButton_Imagen2.getIcon()));
        } else if(this.jRadioButton_Imagen3.isSelected()) {
            ((Jugador) this.jugador).setAvatar(new Avatar(this.jRadioButton_Imagen3.getIcon()));
        } else if(this.jRadioButton_Imagen4.isSelected()) {
            ((Jugador) this.jugador).setAvatar(new Avatar(this.jRadioButton_Imagen4.getIcon()));
        }
    }
    
    public void mostrarMensaje(String mensaje, String titulo, int tipoDeMensaje) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipoDeMensaje);
    }
}
